### ISSUE TITLE
Automate Meetups

### ISSUE THREAD

**Issue by mschonfinkel** [pug-ma/PUGMA-bot#11]
The bot currently fetches data from [this repo](https://github.com/pug-ma/meetups/tree/master/encontros) to get the meetup info + the pictures.

We could do it better by automating this process, maybe via web scraping or better, we could have a meetup API.

**Comment by AntLouiz** [comment]
Working on it :)

**Comment by lucassouto** [comment]
Added integration with github api to check meetups
